"""add_trade_plan_json_to_ta_signals

Revision ID: 787c76271bd9
Revises: 001
Create Date: 2025-12-22 19:16:40.035702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787c76271bd9'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta_signals', sa.Column('trade_plan_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ta_signals', 'trade_plan_json')
    # ### end Alembic commands ###
